meta-rust/meta-rust

recipes/rust/rust.inc

In dizzy, the following error was encountered when running do_install
on the rust recipe:
pushd: not found
According to the bitbake user manual, /bin/sh is used and bashisms
(like pushd) should be avoided.  In my case, /bin/sh turns out to
be zsh (with no extra configuration, so pushd is not present).
Signed-off-by: Paul Osborne <osbpau@gmail.com>

rust: replace pushd usage in rust do_install

---

recipes-deps/libgit2/libgit2.inc

This resolves https://github.com/jmesmon/meta-rust/issues/1.  This
change is only necessary for systems (like dizzy) that do not
contain poky commit 60d504b431fa7cdc6ded141def7ae18edb1834e5.
Without that commit or this change, do_compile for libgit2 would fail
with the following error:
CMAKE_AR-NOTFOUND cr libgit2.a  ...
Error running link command: No such file or directory
Signed-off-by: Paul Osborne <osbpau@gmail.com>

libgit2: dizzy: tell cmake to use ${AR} for the linker

---

recipes/rust/rust.inc

Depending on gcc-cross is a general bug that should be fixed.  For non-hard-float ARM systems, we should use ${RUST_TARGET_SYS} instead of a hard-coded triplet.
Verified that rustc generates an executes that runs on HW.

Fixes for building rust-cross-arm

---

recipes/rust/rust-llvm-native_1.1.0.bb
recipes/rust/rust-release.inc
recipes/rust/rust.inc
recipes/rust/rust_1.1.0.bb

rust takes a painfully long time to build.  A non-trivial part of that
is building LLVM.  Fortuitiously, the LLVM component is common between
the -native compiler and all variants of the -cross compiler.  That
means we can build it once, and reuse the output for any flavor of rust.
That saves build time, and it utilizes bitbake's sstate more
efficiently.  It's win/win!

Make LLVM in its own recipe

---

recipes/rust/files/rust-1.1.0/0009-src-rt-arch-i386-morestack.S-call-rust_stack_exhaust.patch
recipes/rust/files/rust-1.1.0/0010-disable-symbol-version-hashing.patch
recipes/rust/rust_1.1.0.bb

Rust's symbol hashes break sstate, because a subsequent build of the same
input hash may generate different symbol hashes.  This means that
packages that previously built against the "same" (from bitbake's
perspective) rustc would no longer run, and bitbake would not know to
rebuild them because the input hash is the same.
Fortunately, bitbake's input hash makes rust's symbol versions
unnecessary; any change to rust's source or configuration will cause
rustc and all dependencies to rebuild.  Therefore, it's safe to defeat
rust's symbol versions entirely with a static version.

Disable symbol hashing

---

classes/rust-bin.bbclass
recipes/rust/rustlib.bb

rustlib.bb packages up the rust runtime for inclusion in the final image.  rust-bin.bbclass can be used to build rust libraries and binaries without cargo (because cargo can't play nice with bitbake's fetcher yet)

Add rustlib.bb and rust-bin.bbclass

---

recipes/rust/rust-llvm.inc

This fixes the assertion failure and allows 1.2.0 to successfully build

rust-llvm.inc: fix configure flags to match was rust uses

---

conf/layer.conf

The path in LICENSE_PATH was not the correct path to where the licenses
are located in this repo.
Signed-off-by: Doug Goldstein <cardoe@cardoe.com>

fix LICENSE_PATH location

---

conf/licenses.conf

Per conversation in #rust with kergoth this file is causing a backtrace
in bitbake because its overriding the meta/conf/licenses.conf file. The
behavior that's expected out of this isn't valid with newer Yocto
releases so its possible this is for an older version.
Signed-off-by: Doug Goldstein <cardoe@cardoe.com>

remove conf/licenses.conf

---

conf/distro/include/rust_security_flags.inc
conf/layer.conf

When someone is using a distro that's using security flags we need to
provide overrides to disable PIE.
Signed-off-by: Doug Goldstein <cardoe@cardoe.com>

Provide distro config include for security flags

---

recipes/rust/files/rust-1.5.0/0010-rustc_trans-make-.note.rustc-look-more-like-debug-in.patch
recipes/rust/rust.inc
recipes/rust/rust_1.5.0.bb

Rust programs included in prelinked images often crash at boot.
The reason prelink seemed to break relocations in .bss is because the
.note.rustc section happened to be placed in front of .bss. Using
objcopy to strip the note renumbered the sections and the symbols in the
.dynsym section were pointing to the wrong section index, but only for
.bss. Prelink would skip updating these dyn entries because it thought
they were pointing to a section that didn't get relocated, like
.comment. In some cases the GOT was actually prelinked correctly, but
the dynamic linker at run time would modify it to point at the
non-prelinked address.
Removing the SHF_ALLOC flag from the section causes it to be placed at
the end of the executable where it can be safely removed.
This is still a hack to the …

Fix prelink issue breaking .bss

---

classes/rust.bbclass
recipes/rust/files/rust-1.5.0/0011-Allow-overriding-crate_hash-with-C-crate_hash.patch
recipes/rust/files/rust-1.5.0/0012-mk-platform.mk-pass-C-crate_hash-to-builds.patch
recipes/rust/rust.inc
recipes/rust/rust_1.5.0.bb

The current crate hash is not stable from run-to-run.  This causes
problems with bitbake; it needs a guarantee that every build with the
same input will generate compatible output, otherwise sstate won't work.
Using -C crate_hash, we can do that by using the bitbake input hash to
determine the crate hash; the bitbake input hash will be stable, but
still different for different rust recipes.
This should eliminate the problems that have been seen when bitbake
rebuilds part of the rust stack (due to missing sstate) and ends up
getting hash mismatches.  Unlike rust's internally generated hash, ours
is guaranteed to be stable.

rust: force crate hash to use bitbake input hash

---

classes/rust.bbclass

Remove the newly introduced (in poky) --disable-static which is not recognized by the rust configure scripts.
Fixes #40

Remove the '--disable-static' in the EXTRA_OECONF for all rust-like recipes

---

classes/rust-bin.bbclass
recipes-core/libc/libc-rs_0.2.5.bb
recipes-devtools/rust/files/rust/0001-Add-config-for-musl-based-arm-builds.patch
recipes-devtools/rust/rust-snapshot-2015-12-18.inc
recipes-devtools/rust/rust-source.bb
recipes-devtools/rust/rust.inc
recipes-devtools/rust/rustlib.bb

Most importantly, update the stage0 snapshot so that it actually accomplishes something.  Additionally, improve support for running on tiny Linux systems with support for musl libc and static linking.

Several fixes for rust 1.7

---

recipes-deps/libgit2/libgit2.inc

If this dependency is missing its possible that openssl won't be built
before libgit2 is built and then we won't have git support over SSL
which leaves out a lot of git repos. Should fix the issue mentioned in #53.

libgit2: add a dependency on openssl

---

classes/cargo.bbclass
classes/rust-bin.bbclass
classes/rust.bbclass
recipes-devtools/cargo/cargo_0.10.0.bb
recipes-devtools/cargo/files/0001-disable-cargo-snapshot-fetch.patch
recipes-devtools/cargo/files/ssh2-rs/0001-libssh2-sys-avoid-explicitly-linking-in-openssl.patch

Move some variables from `rust-bin.bbclass` to `rust.bbclass`, working toward commonality between rust-bin and cargo.
The new version of cargo allows a couple `cargo.bbclass` hacks to be removed.
I tested that dynamically-linked rust-bin apps execute on the generated target image and rust-hello-world (cargo) builds.

Update Cargo, bbclass cleanup

---

classes/cargo_util.bbclass
classes/crate-fetch.bbclass
lib/crate.py
recipes-example/rust-hello-world/rust-hello-world_git.bb
recipes-example/rustfmt/rustfmt_0.4.0.bb

This adds a custom fetcher for Cargo crates and hopefully will simplify adding Cargo based projects to meta-rust. The URL syntax is:
`crate://HOST/NAME/VERSION` with a standard example being `crate://crates.io/memchr/0.1.11`
Additionally this supports fetching down a snapshot of the registry index for reproducible builds with the syntax:
`crate-index://HOST/REVISION` with an example being `crate-index://crates.io/3b3994e099281c394a6a66604d1af6c0920e4c31`
`crates.io` as a HOST magically fixes up the paths to hit the official registry. This should be able to support custom registries should people want to use them as well.
Fixes #24. Might close #12.

add a custom fetcher for Cargo crates

---

classes/shared-source-use.bbclass

The oe-core/poky change 'base.bbclass wipe ${S} before unpacking
source' (poky: a56fb90dc3805494eeaf04c60538425e8d52efc5, oe-core:
eccae514b71394ffaed8fc45dea7942152a334a1) wipes ${S} in do_unpack prior
to unpacking. This breaks our shared source as we set ${S} to the shared
location, and don't actually unpack anything (the result is we try to
build rustc without any source code, which fails predictably)
Avoid this by copying a bit more of gcc-shared-source.inc to disable
do_unpack for shared source users.
This is a bit of a hack, and only barely works (due to our need for
rust-snapshot). In the future, it might make sense to have the
rust-snapshot be shared in some fashion as well (which would allow us to disable fetch and more closely mimic gcc-shared-source.inc).

rustc: fix use of shared source for new poky/oe-core which wipes ${S}

---

recipes-devtools/rust/files/rust/fix-urandom-during-init.patch
recipes-devtools/rust/rust-source.bb

Signed-off-by: Derek Straka <derek@asterius.io>

rust: add a backport fix to use /dev/urandom in cases where the random m pool isn't yet initialized

---

recipes-devtools/rust/compiler-rt.bb

OE-Core rev aeb653861a0ec39ea7a014c0622980edcbf653fa (between jethro and
krogoth) removed -e from the default flags in EXTRA_OEMAKE. Without
this, the makefile will default to gcc for CC.

compiler-rt: ensure -e is passed to make

---

recipes-devtools/cargo/cargo.inc

Not sure why this is starting to affect cargo now, but let's fix it.

cargo: avoid build failure due to --disable-static not being recognized

---

recipes-devtools/rust/rust-cross.bb

By copying exactly the target we intend to.
Fixes #77 
Testing with new enough poky may also need #78

rust-cross: fix build where TARGET_ARCH and HOST_ARCH are the same

---

recipes-deps/libgit2/libgit2.inc

Without these dependencies cargo is unable to fetch packages from SSH
based repos. This same fix is already upstream in meta-oe master at:
http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-support/libgit2/libgit2_0.24.1.bb

libgit2: add missing dependencies

---

recipes-devtools/rust/rust.inc

Fixes #47 
Fixes #65  (though might have actually been fixed earlier).
Also includes a few other cleanups.
These changes are extracted from #85 , just removing the commit that merges the building of rust's llvm back into rust itself.

Ensure proper CXXFLAGS & CFLAGS are passed to rust's `rustllvm` component (c++ files built as part of rustc)

---

Jenkinsfile
conf/bblayers.conf.sample
conf/local.conf.sample
scripts/build.sh
scripts/cleanup-env.sh
scripts/containerize.sh
scripts/fetch.sh
scripts/setup-env.sh

This adds some scripts to build `rustfmt` using all of our tooling inside of a Docker container to ensure that all the dependencies are there. In theory anyone should be able to use this on their machine and confirm the same results. It should be possible to extend these scripts for building more items and potentially artifacting results for more tests. fixes #94

Jenkins CI

---

.gitignore
conf/local.conf.sample
recipes-devtools/rust/rust-llvm.inc
recipes-devtools/rust/rust-llvm_1.10.0.bb
scripts/build.sh
scripts/containerize.sh
scripts/fetch.sh

Some additional cleanups I've queued after #101 lands.
- combine some `rust-llvm` bits that never made it into master and have been in fido and the starlab-io fork.
- fix the fetch script that Jenkins uses if a user decides to use it for testing to default to a sensible value
- change the default target machine to x86_64 from i586.
This is based on #101.

Small cleanups

---

recipes-devtools/rust/rust.inc

The data layout changed for Rust 1.10. I noticed this because I got a
crash when using rust-native to build rust. The assertion that hit was
saying data layout mismatch and caused me to check the values in the
Rust sources.

rust: fix LLVM data layouts for Rust 1.10

---

.github/ISSUE_TEMPLATE.md

I don't think we really need much structure, but in many cases
establishing the version of meta-rust which contains the issue is very
helpful in resolving it.
This makes it so the issue-reporter is at least given a field which
asks for the version.

github: add issue template to encourage reporting meta-rust version

---

classes/rust-triples.bbclass
classes/rust.bbclass

Improve how we generate the native Rust triples from `TARGET_SYS`, `BUILD_SYS`, and `HOST_SYS` to hopefully more accurately generate these. This should solve issues with i586/i686 and musl based systems. Hopefully this future proofs the behavior for further support landing in upstream.

Improve Rust triple generation

---

classes/rust.bbclass
recipes-devtools/rust/compiler-rt_1.10.0.bb
recipes-devtools/rust/rust.inc

Found some commented out bits that can just get cleaned up. Removed a call to `env` that was dumping into the logs. And lastly updated compiler-rt to be built closer to how upstream builds it instead of passing in the entire environment in.

Update compiler-rt build and remove commented out bits

---

Jenkinsfile
classes/cargo.bbclass
classes/rust-bin.bbclass
classes/rust.bbclass
recipes-devtools/cargo/cargo.inc
recipes-devtools/rust/rust.inc

Refactors the Yocto linker flags out of the custom targets and into the rustflags option of the cargo config. This is part of my series to eventually allow us to use the native targets and slim down the delta between upstream Rust/Cargo and what's in meta-rust.

refactor linker flags out of custom targets

---

Jenkinsfile

Rename the stages to ensure that the machine name is in there so its
easier to track what machine is currently being built.

Jenkinsfile: rename stages for easier tracking

---

classes/rust-bin.bbclass
classes/rust-common.bbclass

The -C crate_hash option does not work if multiple versions of the same
crate are being linked into a binary. This can happen if different
dependencies depend on different versions of the same crate. The -C
crate_hash argument causes all versions of a given crate to have the
same crate hash which in turn causes the compiler to select the wrong
one internally and crash. This works around issue #126 for Cargo builds
but does not fix the underlying cause.

workaround bug in the -C crate_hash option

---

recipes-devtools/rust/compiler-rt_1.10.0.bb
recipes-devtools/rust/compiler-rt_1.12.1.bb

Fix building a toolchain installer with bitbake
-c populate_sdk in packages compiler-rt,
compiler-rt-dev and compiler-rt-staticdev.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

compiler-rt: fix toolchain installer

---

recipes-devtools/rust/rust.inc

rust: fix cpu selection so older processors can run executables for rust-native

---

recipes-devtools/rust/rust-llvm.inc

The way LLVM builds its native utilities is not safe (it runs a
recursive cmake in the same work directory as the main instance).  To
prevent those instances from stepping on each other, we'll build the two
native utilities separately before starting the main build.
Fixes issue #143

rust-llvm.inc: work around build race

---

Jenkinsfile
conf/local.conf.sample
scripts/publish-build-cache.sh

Before this PR, all builds would run without and use of SSTATE cache.  With this addition, the build times can be significantly reduced.

Add the ability to use and store build cache artifacts

---

recipes-devtools/rust/rust-llvm.inc
recipes-devtools/rust/rust-llvm_1.15.1.bb

This is already accounted for by the LLVM CMake files, assuming
CMAKE_CROSSCOMPILING is set correctly, which is fixed in the upstream
cmake.bbclass.
http://git.openembedded.org/openembedded-core/commit/?id=bd082c9be6191e67ea1b1bf10ce5e130a3433ab5

rust-llvm: Drop unnecessary native customization

---

classes/cargo.bbclass
classes/rust-bin.bbclass
classes/rust-common.bbclass
classes/rust.bbclass
recipes-core/aho-corasick/aho-corasick-rs_0.2.1.bb
recipes-core/bitflags/bitflags_0.8.2.bb
recipes-core/libc/libc-rs_0.2.21.bb
recipes-core/libc/libc-rs_0.2.5.bb
recipes-core/memchr/memchr-rs_0.1.11.bb
recipes-core/regex/regex-rs.bb
recipes-core/regex/regex-syntax-rs.bb
recipes-core/time/time-rs_0.1.38.bb

We finally got around to upgrading to rust 1.20/1.21 internally.  We had to make some changes to rust-bin.bbclass to get everything working again.
@meta-rust/maintainers

rust-bin.bbclass fixes

---

classes/rust-common.bbclass
recipes-devtools/rust/files/rust-1.21.0/0001-Don-t-use-remapped-path-when-loading-modules-and-inc.patch
recipes-devtools/rust/files/rust-1.21.0/0001-librustc-always-allow-unstable-options.patch
recipes-devtools/rust/rust_1.21.0.bb

With these changes, we're getting compatible output from the compiler with stable crate hashes even across build machines and workspaces.  This supercedes the old -C crate_hash compiler flag that we had previously used to ensure compatibility.
The patch to fix path remapping is a backport of an already-upstreamed fix, so that patch should not need to be rebased in the next upgrade.

Make rustc output reproducible

---

recipes-devtools/rust/rust.inc

The "target_c_int_width field is added to librustc_back since rust 1.22.0 because not all rust targets (e.g. msp430-none-elf, avr) have 32-bit int types any more.
This will probably be needed when updating to rust 1.22+

rust: specify target-c-int-width

---

recipes-devtools/rust/rust-llvm.inc

This works out in recent poky releases because cmake_do_compile ends up
in oe_runmake via base_do_compile, but this changed recently to allow
cmake's generic `cmake --build` feature to call the appropriate
generator instead of always assuming make.
http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit?id=579d17ba5f722edb9fe79682480c4a9508ad0ed4

rust-llvm: remove custom do_compile

---

recipes-devtools/rust/libstd-rs.inc

When yocto is searching for lib dependencies it uses SONAMES and RPATHS to find
the right one. When we compile a rust package which dynamically links to rust's
libstd, yocto will not be able to find the matching dependency in shlib and
will complain with a warning. Even worse, if you have compiled go-runtime, the
build will find go-runtime as provider of libstd and will complain that you
missed a RDEPENDS to go-runtime - this is completely wrong obviously.
This patch adds SONAME to rust's stdlib. In this way yocto will create the
required provider and packages dynamically linking to it will be able to find
libstd-rs as a provider of stdlib.
Signed-off-by: Andrei Gherzan <andrei@resin.io>

libstd-rs: Set SONAME for libstd.so

---

classes/cargo.bbclass
classes/rust-common.bbclass
conf/layer.conf
recipes-devtools/cargo/cargo-0.27.0.inc
recipes-devtools/rust/rust-llvm.inc
recipes-devtools/rust/rust-snapshot-1.26.2.inc
recipes-devtools/rust/rust.inc

This is a few smaller fixes and tweaks I've come up with.
First is if you set DEBUG_BUILD="1" in a cargo recipe, cargo will build without --release. This mimics DEBUG_BUILD pretty well (it sets "-O0 -g" etc in normal builds). set DEBUG_BUILD_pn-whateverpackage = "1" in conf/local.conf for much shorter compile times.
Second is a change which installs rust-llvm into a subdir instead of ${prefix} as usual. It makes it possible to use meta-rust and meta-clang together. It should also fix #173.
Third adds the possibility to use TCLIBC="musl". I.e. replace glibc with musl. It seems to work and rust applications are dynamically linked to musl. Can be good to decrease the size of firmwares. It is even possible to use meta-clang, meta-rust and musl together.
Forth is adding rocko as a compatible …

Various fixes, Clang, TCLIBC, DEBUG_BUILD, rocko 

---

recipes-devtools/rust/libstd-rs.inc

When DEBUG_BUILD is set in conf/local.conf, libstd-rs fails to build

libstd-rs: support debug builds

---

recipes-devtools/rust/libstd-rs.inc
recipes-devtools/rust/libstd-rs_1.26.2.bb

This will allow features to be easily modified through a bbappend file
in another layer.
The last local commit we had to meta-rust was for this purpose.  This commit would allow us to replace our local commit with a bbappend instead.

libstd-rs: use a separate variable for --features

---

classes/rust-common.bbclass

Before the flag was stabilized, it required two arguments of the form
"from=<from_path>" and "to=<to_path>" respectively. The stabilized
version uses one argument of the form "<from_path>=<to_path>".
Unfortunately the old format is still parsed successfully, but results
in attempting to replace the literal paths "from" and "to".
https://github.com/rust-lang/rust/issues/41555#issuecomment-320951103

rust-common: fix remap-path-prefix for 1.26

---

recipes-devtools/rust/rust-llvm.inc
recipes-devtools/rust/rust-llvm/0002-llvm-allow-env-override-of-exe-path.patch
recipes-devtools/rust/rust.inc

This make llvm cross build work better and we can compile libstd-rs, target rust still fails with SIGSEGV in rustc but that was failing always

Fix building llvm (inspirations from meta-clang)

---

classes/cargo_common.bbclass

`TARGET_CFLAGS` is used twice, copying `CXXFLAGS` into `TARGET_CFLAGS`.
I have a recipe failing to build because some C++-only flags are being appended to `CFLAGS`. It looks like this is the source of the issue. Making the change below solved the issue.

Fix TARGET_CXXFLAGS in cargo_common

---

recipes-devtools/rust/libstd-rs.inc

if ${B}/${TARGET_SYS}/release/deps/*.d is empty the build fails
with the -f flag it ignores if that is empty..
This happens on sumo if `PREFERRED_VERSION_cargo-native = 0.22.%` is set.
due to #220

libstd don't fail if incremental build files don't exist (sumo)

---

recipes-devtools/rust/libstd-rs.inc

musl builds need libunwind.a to be in sysroot for libstd-rs to build
unwinding support into it. This also means we need to compile libunwind
with --enable-static in oe-core

libstd-rs: Depend on libunwind on musl builds

---

recipes-devtools/rust/rust.inc

This ensures that rust-cross can be compiled for ppc arch

rust-cross: Add ppc support

---

classes/cargo_common.bbclass

This is needed for cargo to use proxies set by bitbake. It is important
for devtooled builds which does not use vendored sources.

Set proxy in cargo if available

---

recipes-devtools/rust/rust.inc

ARM_INSTRUCTION_SET, and therefore ARM_THUMB_OPT also, expect to only be
used in conjunction with the thumb TUNE_FEATURES. So thumb-mode should only
be added if thumb is in TUNE_FEATURES and ARM_THUMB_OPT is thumb.
The commit https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/meta/conf/machine/include/arm/arch-armv7a.inc?id=3e7d26e31a724009e69788460737e07163a14051
caused armv7a.inc to set ARM_INSTRUCTION_SET to thumb and the commit
message explicitly states that the change should have no effect unless
TUNE_FEATURES also includes thumb. This change to rust will allow that
assumption to continue to be true.

rust: don't configure thumb if not in TUNE_FEATURES

---

recipes-devtools/cargo/cargo/0001-Disable-http2.patch
recipes-devtools/rust/rust-llvm_1.34.2.bb
recipes-devtools/rust/rust-source-1.34.2.inc

1.34.2 changes a number of license texts and a new patch fuzz warning in cargo

Fix checksums and patch fuzz from 1.34.2

---

recipes-devtools/rust/rust.inc

This was generated with:
clang --target=riscv32  -emit-llvm -S -x c /dev/null -o aaa |  cat aaa | grep "target datalayout"
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

rust-cross: Add riscv32 data layout information

---

classes/cargo_common.bbclass

This solves issue #246 
When a sstate-cache is used sometimes the certificates are not available at the compile time path anymore. Typically they point to a file that existed when building another package. Possibly even another user it a shared sstate-cache is used. The required certificates are available in sysroot-native and can be selected with the cainfo configuration instead to solve the connection problems.

Set cainfo to certificates in sysroot-native

---

recipes-devtools/cargo/cargo-1.37.0/0001-Disable-http2.patch
recipes-devtools/cargo/cargo_1.37.0.bb
recipes-devtools/rust/libstd-rs_1.37.0.bb
recipes-devtools/rust/rust-cross_1.37.0.bb
recipes-devtools/rust/rust-llvm_1.37.0.bb
recipes-devtools/rust/rust-snapshot-1.37.0.inc
recipes-devtools/rust/rust-source-1.37.0.inc
recipes-devtools/rust/rust_1.37.0.bb

I don't know your policy regarding removal of old versions, so I kept all existing Rust and Cargo versions.
Build has been tested locally. Works after also applying https://github.com/meta-rust/meta-rust/pull/247

Update to Rust and Cargo 1.37.0.

---

recipes-devtools/rust/rust.inc

Since https://github.com/openembedded/openembedded-core/commit/ac83d22eb5031f7fdd09d34a1a46d92fd3e39a3c
The armvX arch definition is not present in TUNE_FEATURES but is now in
MACHINEOVERRIDES. Improve parsing so that MACHINEOVERRIDES is also checked.
Fixes #240
Tested on raspberrypi3 with balenaOS which uses rust.
Signed-off-by: Zubair Lutfullah Kakakhel <zubair@balena.io>

rust: Improve TUNE_FEATURE parsing

---

recipes-devtools/rust/rust-llvm.inc
recipes-devtools/rust/rust.inc

Use Python3 as the native Python instead of Python2.
Signed-off-by: Alistair Francis <alistair@alistair23.me>

rust: Use Python3 native for build

---

classes/rust-common.bbclass

Super insignificant micro-optimisation:
`exec` from shell wrapper to avoid persistent sh process

Avoid extra sh process from shell wrapper

---

recipes-devtools/rust/rust-cross.inc
recipes-devtools/rust/rust.inc

The whole point of rust-native is that it should be common for all
targets.  If we reference TARGET variables during the build of
rust-native, then bitbake will build a different version for different
TARGETS.

rust-native shouldn't depend on TARGET variables

---

recipes-devtools/rust/rust.inc

d55cce6b8b6b510bf4905f19b949f7995af57a4d added a use of
BB_NUMBER_THREADS which is not whitelisted in Poky. This caused machines
with a different number of CPUs to have different sstate for
rust-native.

rust.inc: whitelist BB_NUMBER_THREADS in do_compile

---

recipes-devtools/rust/rust.inc

* BB_NUMBER_THREADS is number of bitbake tasks running in
parallel, not parallelization inside individual tasks
* use oe.utils.parallel_make_argument to make sure it
works even when people add e.g. "-l 10" in PARALLEL_MAKE
* with the recent improvements for rust-native build time, I wanted
to rerun some build time tests from
https://github.com/shr-project/test-oe-build-time
here are the results on AMD Threadripper 3970x with 128GB ram:
BB is BB_NUMBER_THREADS
PM is PARALLEL_MAKE
```
TIME   BB        PM   Description
20:50   *         *   zeus based build with 1.37 rust (BB/PM has no impact)
14:50   8  32,48,64   dunfell, 1.43 as in https://github.com/meta-rust/meta-rust/commit/d2ff87ca5545b8081b16ac8f53ed4295593208c6 (PM has no impact, because bootstrap uses BB)
9:50   8  32,48,64 …
```

rust: use PARALLEL_MAKE instead of BB_NUMBER_THREADS

---

recipes-devtools/cargo/cargo.inc

libgit2 0.28.x is shipped by latest Yocto Dunfell.
According to https://github.com/rust-lang/git2-rs/issues/458#issuecomment-522567539, there are no compatibility guarantees between libgit2-sys and arbitrary system libgit2 versions, so better keep this turned off.
Fixes "invalid version 3 on git_proxy_options" during build.
Further references:
* https://github.com/rust-lang/rust/issues/63476
* https://github.com/rust-lang/git2-rs/issues/458
* https://bugs.gentoo.org/707746#c1

Disable LIBGIT2_SYS_USE_PKG_CONFIG due to incompatibility with libgit2 0.28.x

---

classes/rust-bin.bbclass

this is undefined behavior in bitbake, prepend space instead

rust-bin.bbclass: Do not use append and += together

---

recipes-devtools/cargo/cargo-1.46.0/0001-Disable-http2.patch
recipes-devtools/cargo/cargo_1.46.0.bb

Rust version 1.46.0 was added to the layer a while back, but the
corresponding cargo recipe seems to have been missed.

cargo: add missing version 1.46.0

---

classes/rust-common.bbclass
recipes-devtools/rust/rust.inc

arm-unknown-linux-gnueabihf was incorrectly used instead of
armv7-unknown-linux-gnueabihf when building for some Cortex A SoCs.
This may cause segfaults in non trivial rust applications on ARMv7
when e.g. +a7 is passed to LLVM. It seems to differ between different
versions of the compiler and LLVM versions.

Use proper llvm-target for armv7

---

classes/cargo.bbclass
classes/cargo_common.bbclass
recipes-devtools/cargo/cargo.inc

The first commit enables build separation where the build directory is placed outside of the source directory. This is how most packages are built with bitbake and makes it possible to share the source directory between different machines without risking cross contamination.
The second simply makes cargo_home/config a bit more readable with in-line descriptive comments. The content should be identical.

Build separation

---

recipes-devtools/rust/rust.inc

This now matches with llvm target backend in llvm 11

rust: Correct the data layout for riscv32

---

recipes-devtools/rust/libstd-rs.inc
recipes-example/rust-hello-world/rust-hello-world/0001-enable-LTO.patch
recipes-example/rust-hello-world/rust-hello-world_git.bb

Fixes #294.
Also enables LTO for `rust-hello-world` to try and catch regressions in future.

libstd-rs: embed bitcode for LTO

---

classes/cargo.bbclass

Fixes dependency loop
These are usually caused by circular dependencies and any circular dependency chains found will be printed below. Increase the debug level to see a list of unbuildable tasks.
Identifying dependency loops (this may take a short while)...
ERROR:
Dependency loop #1 found:
Task virtual:native:/mnt/b/yoe/master/sources/meta-rust/recipes-devtools/cargo/cargo_1.47.0.bb:do_compile (dependent Tasks ['cargo_1.47.0.bb:do_configure'])
Task virtual:native:/mnt/b/yoe/master/sources/meta-rust/recipes-devtools/cargo/cargo_1.47.0.bb:do_install (dependent Tasks ['cargo_1.47.0.bb:do_compile'])
Task virtual:native:/mnt/b/yoe/master/sources/meta-rust/recipes-devtools/cargo/cargo_1.47.0.bb:do_populate_sysroot (dependent Tasks ['cargo_1.47.0.bb:do_install'])
Task …

cargo: Mark the cargo-native dependency specific to target

---

recipes-devtools/rust/rust-snapshot-1.34.2.inc
recipes-devtools/rust/rust-snapshot-1.36.0.inc
recipes-devtools/rust/rust-snapshot-1.37.0.inc
recipes-devtools/rust/rust-snapshot-1.39.0.inc
recipes-devtools/rust/rust-snapshot-1.40.0.inc
recipes-devtools/rust/rust-snapshot-1.41.0.inc
recipes-devtools/rust/rust-snapshot-1.43.0.inc
recipes-devtools/rust/rust-snapshot-1.46.0.inc
recipes-devtools/rust/rust-snapshot-1.47.0.inc
recipes-devtools/rust/rust-snapshot.inc
recipes-devtools/rust/rust-source-1.34.2.inc
recipes-devtools/rust/rust-source-1.36.0.inc
recipes-devtools/rust/rust-source-1.37.0.inc
recipes-devtools/rust/rust-source-1.39.0.inc
recipes-devtools/rust/rust-source-1.40.0.inc
recipes-devtools/rust/rust-source-1.41.0.inc
recipes-devtools/rust/rust-source-1.43.0.inc
recipes-devtools/rust/rust-source-1.46.0.inc
recipes-devtools/rust/rust-source-1.47.0.inc
recipes-devtools/rust/rust-source.inc
recipes-devtools/rust/rust.inc

I've also updated https://github.com/meta-rust/meta-rust/pull/293 with these (and previous) cleanups, it's in jansa/lic-1.49.0 branch (see https://github.com/meta-rust/meta-rust/compare/master...shr-project:jansa/lic-1.49.0?expand=1)

Few more cleanups

---

recipes-devtools/cargo/cargo-1.49.0/0001-Disable-http2.patch
recipes-devtools/cargo/cargo_1.49.0.bb
recipes-devtools/rust/libstd-rs_1.49.0.bb
recipes-devtools/rust/rust-cross_1.49.0.bb
recipes-devtools/rust/rust-llvm_1.49.0.bb
recipes-devtools/rust/rust-snapshot-1.49.0.inc
recipes-devtools/rust/rust-source-1.49.0.inc
recipes-devtools/rust/rust.inc
recipes-devtools/rust/rust/0001-rustc_target-Fix-dash-vs-underscore-mismatches-in-op.patch
recipes-devtools/rust/rust_1.49.0.bb

Now it seems `./x.py install` is the only way to assemble a fully
working stage 2 cross-built compiler. See rust-lang/rust#81702.
Fixes #292.

add rust 1.49.0

---

classes/cargo.bbclass
recipes-devtools/cargo/cargo.inc

Normally all *-native packages needs to depend on cargo-native in order
to be able to use cargo. When building cargo-native however, this is not
available and we use a snapshot.
Fixes #302.

Fix *-native cargo builds

---

recipes-devtools/rust/rust.inc

Building for "+v8.1a"  breaks on (at least) Cortex A53 (Armv8-A) on startup with `Illegal instruction`.
Fixes: 26609f46d93c ("rust.inc: use 'v8.1a' feature when building for aarch64 instead of 'v8'")

rust: Drop v8.1a tune for aarch64

---

classes/cargo.bbclass

Fixes Cargo workspace builds, see #309 . There is an alternative PR up within `cargo-bitbake` https://github.com/meta-rust/cargo-bitbake/pull/23.

Factor in `CARGO_SRC_DIR` when setting `MANIFEST_PATH`.

---

recipes-devtools/rust/rust.inc

This function has a long history, which is worth telling:
* It was added in https://github.com/meta-rust/meta-rust/commit/ba16b5c39e3a23452a98a88d1ca58da0448f97f0 with the same idea: Optimize for 32-bit Core2 or 64-bit Core i7 if possible, otherwise select the closest generic x86 CPU, otherwise select a completely generic CPU. This implementation had two flaws:
* It used a single translation table for two variables (`TUNE_PKGARCH` and `TRANSLATED_TARGET_ARCH`), making it hard to guess where a certain value comes from and whether one is still needed.
* It used `TUNE_PKGARCH`, which is an arbitrary CPU description that everyone can make up with an own machine definition. Hence, this list can never be complete.
* `TUNE_PKGARCH` was replaced by `PACKAGE_ARCH` in …

Revamp llvm_cpu to select the closest CPU for optimization.

---

classes/cargo.bbclass

this enables installing example executables without having to override cargo_do_install()

install example executables

---

recipes-devtools/rust/rust.inc

this helps building the compiler, work is still needed for libstd-rs and
other pieces

rust: Enable ppc64le target

---

recipes-devtools/rust/rust-llvm.inc
recipes-devtools/rust/rust-llvm/0001-nfc-Fix-missing-include.patch
recipes-devtools/rust/rust-llvm/0002-llvm-allow-env-override-of-exe-path.patch

Backport a patch from upstream llvm
Fixes build errors like
```
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/rust-llvm/1.49.0-r0/rustc-1.49.0-src/src/llvm-project/llvm/utils/ben
chmark/src/benchmark_register.h: In function 'void AddRange(std::vector<T>*, T, T, int)':
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/rust-llvm/1.49.0-r0/rustc-1.49.0-src/src/llvm-project/llvm/utils/ben
chmark/src/benchmark_register.h:17:30: error: 'numeric_limits' is not a member of 'std'
|    17 |   static const T kmax = std::numeric_limits<T>::max();
|       |                              ^~~~~~~~~~~~~~
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/rust-llvm/1.49.0-r0/rustc-1.49.0-src/src/llvm-project/llvm/utils/ben
chmark/src/benchmark_register.h:17:46: error: expected …
```

rust-llvm: Fix build with gcc11

---

recipes-devtools/rust/rust.inc

Needed when compiling with options such as "-C profile-generate" or
"-Z instrument-coverage", e.g. when generating coverage reports or doing
profile guided optimization.

rust.inc: Build the profiler runtime

---

classes/cargo.bbclass
classes/cargo_common.bbclass

Recent versions of cargo support always showing the progress indicator.
By default the progress indicator is hidden if the output is not a tty.
For bitbake builds, the output is redirected to a file and not a tty.
However, if we tell cargo to always show the progress indicator, bitbake
can parse it and will show the user how the rust build is progressing.

cargo.bbclass: support cargo's progress indicator

---

recipes-devtools/rust/rust-common.inc

At GARDENA, we are running our Rust based web interface and overlayfs-purge tool successfully on our ARMv5, Atmel SAM9G25 SoC based IoT gateway.

rust: Add support for ARMv5

---

recipes-devtools/rust/rust-common.inc

Not sure if this is the correct way to do this, but this fixes #337

rust.inc: add strict-align when target is ARMv4

---

recipes-core/packagegroups/packagegroup-rust-cross-canadian.bb
recipes-devtools/rust/rust-cross-canadian.inc

This mimics what rustup packages into the toolchain contents. The
presence of the sources for the exact std lib can be useful for the
development and IDE integration.
Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>

nativesdk: Package rust sources

---

classes/rust-common.bbclass
recipes-core/packagegroups/packagegroup-rust-cross-canadian.bb
recipes-devtools/rust/rust-cross-canadian-common.inc
recipes-devtools/rust/rust-cross-canadian.inc
recipes-devtools/rust/rust-tools-cross-canadian.inc
recipes-devtools/rust/rust-tools-cross-canadian_1.51.0.bb
recipes-devtools/rust/rust.inc

This brings ATM:
- clippy
- rustfmt
Another approach might be to include these into the existing rust recipe,
but as we can't really use PACKAGECONFIG here it might just overload it.
This way, the tools will be built in parallel and still can be excluded
from the packgae group, if desired.
Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>

nativesdk: Add some tools in a separate recipe

---

recipes-devtools/rust/rust-snapshot-1.49.0.inc
recipes-devtools/rust/rust-snapshot-1.51.0.inc

This adds the missing hash values to enable building on a aarch64 based host machine

Added hashes for aarch64 binary snapshot packages

---

recipes-devtools/rust/rust-common.inc

literal is being checked here therefore == and != should be used instead
of 'is' or 'is not'

rust-common.inc: Use == operator instead of 'is'

---

README.md

Signed-off-by: Philippe Coval <philippe.coval@astrolabe.coop>

docs: Fix typo for corresponds

---

conf/distro/include/rust_versions.inc

This was set to a rust version no longer carried in meta-rust. Bumping it to 1.66.0.

rust_versions.inc: bump to latest rust versions

---

recipes-devtools/rust/rust-common.inc

My modernization of this function had a long discussion in PR #319, with 3 reviewers giving their feedback and ultimately approving my commits 83ad3d415f2b5592b8eeea12f404c4e0fcfd1d45 and 81f9357b58a16b0788b2cea9d435998e7b05dafd.
However, these changes got lost when PR #313 was merged later via commit 250230e292d9b2815151e8a8b5e5d603a5140a63.
This restores my changes to the `llvm_cpu` function.

Restore `llvm_cpu` from #319, mistakenly removed when merging #313

---

classes/rust-common.bbclass

In the kirkstone branch and later rust is now available as a dependency for other packages. Among other thing the `python3-cryptography` use some rust binding. Thus it needs to run `rustc --print target-list`. If `RUST_TARGET_PATH` is not exported, then all the `rustc --print` invocation fail with: 
`Error loading target specification: Could not find specification for target "x86_64-linux". Run rustc --print target-list for a list of built-in targets`
This seems like those issue where the fix is to export the `RUST_TARGET_PATH`
https://github.com/rust-lang/cargo/issues/4865#issue-284617845
https://github.com/japaric/xargo/issues/44#issue-178701245
This is an other step toward to fix #380

export RUST_TARGET_PATH

---

conf/distro/include/rust_versions.inc

This was set to a rust version no longer carried in meta-rust (1.66.0). Bumping to latest version 1.72.0.

rust_versions.inc: bump to latest rust version 1.72.0

---

conf/distro/include/rust_versions.inc
recipes-devtools/cargo/cargo-cross-canadian_1.73.0.bb
recipes-devtools/cargo/cargo_1.73.0.bb
recipes-devtools/rust/libstd-rs_1.73.0.bb
recipes-devtools/rust/rust-cross-canadian_1.73.0.bb
recipes-devtools/rust/rust-cross_1.73.0.bb
recipes-devtools/rust/rust-llvm_1.73.0.bb
recipes-devtools/rust/rust-snapshot-1.73.0.inc
recipes-devtools/rust/rust-source-1.73.0.inc
recipes-devtools/rust/rust-tools-cross-canadian_1.73.0.bb
recipes-devtools/rust/rust_1.73.0.bb

- Bump LLVM_RELEASE to 17.0.2 (seen in github rust project `llvm-project/` submodule).
- Update default version from 1.72.0 to 1.73.0

Add Rust 1.73.0

---

recipes-devtools/rust/libstd-rs.inc

Allow rust standard library to be used in SDKs. This is consistent with the rust toolchain that's now included in poky.
Tested with:
```
meta-yocto-bsp       = "kirkstone:3e73216a32a2b01916eb8c555a41579bd69a47aa"
meta-oe              = "kirkstone:8a75c61cce2aa1d6e5a3597ab8fc5a7e6aeae1e4"
meta-rust            = "master:ffc33539efc3cc8cdc1dbad5c723daeb8d1d8b3b"
local.conf:
RUSTVERSION = "1.73.0"
TOOLCHAIN_HOST_TASK:append = " nativesdk-python3-cryptography"
```

libstd-rs: Extend to nativesdk

---

conf/distro/include/rust_versions.inc
recipes-devtools/cargo/cargo-cross-canadian_1.75.0.bb
recipes-devtools/cargo/cargo_1.75.0.bb
recipes-devtools/rust/libstd-rs_1.75.0.bb
recipes-devtools/rust/rust-cross-canadian_1.75.0.bb
recipes-devtools/rust/rust-cross_1.75.0.bb
recipes-devtools/rust/rust-llvm_1.75.0.bb
recipes-devtools/rust/rust-snapshot-1.75.0.inc
recipes-devtools/rust/rust-source-1.75.0.inc
recipes-devtools/rust/rust-tools-cross-canadian_1.75.0.bb
recipes-devtools/rust/rust.inc
recipes-devtools/rust/rust_1.75.0.bb
scripts/rust-get-stage0.sh

Integrate rust 1.75.0 and fixes recipes rust.inc with missing sysconfdir in config.toml.
Also add a minimal shell script which use `jq` to get directly the `stage0.json` from rust github to help update tarball hashes (But do not update recipe directly for now)
Note: Tested on yocto kirkstone.

Add rust 1.75.0

---

recipes-devtools/rust/rust-common.inc

As seen in https://github.com/briansmith/ring/issues/1873, targeting aarch64-poky-linux may not always explicitly have neon in TUNE_FEATURES, but it should also not be removed because it's... there.
With OECore's rust build that works because it's only marked as absent for armv7:
https://github.com/openembedded/openembedded-core/blob/97b5d0c85af0b667854eea90ace0a8c2f51ecefe/meta/classes-recipe/rust-target-config.bbclass#L32
So apply the same here.

Fix incorrect target json for armv8 / aarch64-poky-linux

---

recipes-devtools/rust/rust-common.inc

Akin to b93853c, update the data layout to fix the following build error:
error: data-layout for target `arm-poky-linux-gnueabi`, `e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64`, differs from LLVM target's `armv7-unknown-linux-gnueabihf` default layout, `e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64`
Fixes #444.
~Note that even a rebuild of the Rust toolchain doesn't seem to make this change take effect in an existing Yocto setup. My assumption is that the rust_gen_target function is cached somehow. To fix a build that had this error previously, that function may need to be changed to trigger Yocto to actually generate the correct target JSON file, e.g. by adding a simple log statement. See issue #444 for more information.~
The second commit should address the issue discussed in …

rust-common: Update data layout for armv7-unknown-linux-gnueabihf

---

classes/cargo.bbclass

- I was missing this feature for development builds to enable debug features of an application
- Adds support for enabling disabling Cargo features when building the application through new variables
- Adds support for passing generic flags/arguments to Cargo via `CARGO_EXTRA_FLAGS`
- The newly introduced variables aim to achieve some compatibility with [meta-rust-bin](https://github.com/rust-embedded/meta-rust-bin)
- Using `CARGO_FEATURES` for feature selection
- Providing `CARGO_EXTRA_FLAGS` for an alternative way setting `--all-features` and `--no-default-features`

Add support for Cargo features and flags

---

classes/cargo_common.bbclass

The value of `http_proxy` does not affect the build output and as such should be excluded from the task's hash to avoid sstate cache misses on build hosts with different `http_proxy` settings.

cargo_common: Exclude http_proxy from variable dependencies

---

classes/cargo.bbclass

Export RUSTFLAGS and CARGO_BUILD_TARGET to devshell, 
then can use `bitbake -c devshell recipe` to  enter into devshell, and use cargo build to build directly.
https://doc.rust-lang.org/cargo/reference/config.html#buildtarget

Fix devshell can't work

---

recipes-devtools/rust/rust-common.inc

Rust data layout for aarch64 updated in 1.80.0 release following LLVM data layout update (see: https://github.com/rust-lang/rust/pull/124813).
So conditionally update data layout for aarch64 target build as well.

rust: 1.82.0: Fix builds for aarch64 targets

---

recipes-devtools/rust/libstd-rs_1.82.0.bb

| error[E0463]: can't find crate for `proc_macro`
|   --> /usr/src/debug/pocket/0.1.0.AUTOINC+e82af10ec8-r0/cargo_home/bitbake/proc-macro2-1.0.6/src/lib.rs:86:1
|    |
| 86 | extern crate proc_macro;
|    | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

Fix missing proc_macro for libstd-rs 1.82.0

---

.github/workflows/main.yml
conf/layer.conf

Given this is my first contribution to this project please let me know if this PR or the commits are missing anything that is required.
Comments: 
- NOTE: "langdale" may not be an LTS release, but it is used by certain BSP vendors (such as Xilinx 2024.1).
- WARN: This will likely trigger a merge conflict with the following PR (https://github.com/meta-rust/meta-rust/pull/462).
- NOTE: My fork currently contains a new "langdale" branch at this commit for testing.
Questions:
1. Would it be preferred to push a separate branch named "langdale" and then have this PR be merged into that branch instead?
2. Would it be preferred to branch from an earlier commit, perhaps before or after the commit that added mickledore (https://github.com/meta-rust/meta-rust/pull/423, …

conf/layer.conf: add langdale to layer compat

---

conf/distro/include/rust_versions.inc
recipes-devtools/cargo/cargo-cross-canadian_1.86.0.bb
recipes-devtools/cargo/cargo_1.86.0.bb
recipes-devtools/rust/libstd-rs_1.86.0.bb
recipes-devtools/rust/rust-cross-canadian_1.86.0.bb
recipes-devtools/rust/rust-cross_1.86.0.bb
recipes-devtools/rust/rust-crosssdk_1.86.0.bb
recipes-devtools/rust/rust-llvm_1.86.0.bb
recipes-devtools/rust/rust-snapshot-1.86.0.inc
recipes-devtools/rust/rust-source-1.86.0.inc
recipes-devtools/rust/rust-tools-cross-canadian_1.86.0.bb
recipes-devtools/rust/rust_1.86.0.bb
scripts/rust-get-stage0.sh

Update script/rust-get-stage0 for getting snapshot stage0 sha256sum from script.
Add rust 1.86.0
Warning: Update RUST_VERSION from 1.78.0 to 1.86.0.

Rust 1.86.0

---

.github/workflows/main.yml
classes-recipe
classes/crate-fetch.bbclass
conf/layer.conf
recipes-devtools/rust/libstd-rs_%.bbappend

Fix "could not compile proc-macro2"
