classes/rust-bin.bbclass, recipes-core/crypto/crypto-rs_0.2.31.bb, recipes-core/debug-builders/debug-builders-rs_0.1.0.bb, recipes-core/libc/libc-rs_0.1.8.bb, recipes-core/memchr/memchr-rs_0.1.3.bb, recipes-core/rand/rand-rs_0.3.8.bb, recipes-core/regex/regex-syntax-rs.bb, recipes-core/rustc-serialize/rustc-serialize-rs_0.3.15.bb, recipes-core/time/time-rs_0.1.26.bb, recipes-core/udev/libudev-rs_0.1.2.bb, recipes-core/udev/libudev-sys-rs_0.1.1.bb, recipes-core/udev/libudev-sys-rs_0.1.3.bb, recipes-core/unix-socket/unix-socket-rs_0.4.3.bb, recipes/rust/rust.inc
Add crate recipes for rustc-serialize, debug-builders, unix-socket, rand, and crypto
Additionally, fix up a couple of minor recipe bugs
=> Add more crates

classes/cargo.bbclass, classes/rust-bin.bbclass, classes/rust.bbclass
=> Address parse errors while using getVar to calculate dependency information

classes/shared-source-use.bbclass, recipes/rust/files/rust-llvm/0000-rust-llvm-remove-extra-slash.patch, recipes/rust/rust-llvm.inc, recipes/rust/rust-source.bb
=> Allow the fetch to complete before attempting to patch

Jenkinsfile, conf/bblayers.conf.sample, conf/local.conf.sample, scripts/build.sh, scripts/cleanup-env.sh, scripts/containerize.sh, scripts/fetch.sh, scripts/setup-env.sh
This adds some scripts to build rustfmt using all of our tooling inside of a Docker container to ensure that all the dependencies are there. In theory anyone should be able to use this on their machine and confirm the same results. It should be possible to extend these scripts for building more items and potentially artifacting results for more tests. ref #94 ref #96
=> Jenkins CI

classes/cargo.bbclass, classes/rust-triples.bbclass, recipes-devtools/cargo/cargo.inc
Switched to wrapper scripts over using rustflags from #116. This should hopefully address some of the feedback in #116 after it was merged. These changes additionally fix #76.
=> Continued build updates

classes/cargo.bbclass, lib/crate.py, recipes-devtools/cargo/cargo.inc, recipes-devtools/cargo/cargo_0.11.0.bb, recipes-devtools/cargo/cargo_0.13.0.bb, recipes-devtools/rust/compiler-rt_1.12.1.bb, recipes-devtools/rust/files/rust-1.12.1/0001-Target-add-default-target.json-path-libdir-rust-targ.patch, recipes-devtools/rust/files/rust-1.12.1/0002-mk-for-stage0-use-RUSTFLAGS-to-override-target-libs-.patch, recipes-devtools/rust/files/rust-1.12.1/0003-mk-add-missing-CFG_LIBDIR_RELATIVE.patch, recipes-devtools/rust/files/rust-1.12.1/0005-std-thread_local-workaround-for-NULL-__dso_handle.patch, recipes-devtools/rust/files/rust-1.12.1/0006-mk-install-use-disable-rewrite-paths.patch, recipes-devtools/rust/files/rust-1.12.1/0007-Allow-overriding-crate_hash-with-C-crate_hash.patch, recipes-devtools/rust/files/rust-1.12.1/0008-mk-platform.mk-pass-C-crate_hash-to-builds.patch, recipes-devtools/rust/files/rust-installer-1.12.1/0001-add-option-to-disable-rewriting-of-install-paths.patch, recipes-devtools/rust/libstd-rs_1.12.1.bb, recipes-devtools/rust/rust-cross_1.12.1.bb, recipes-devtools/rust/rust-llvm.inc, recipes-devtools/rust/rust-llvm_1.12.1.bb, recipes-devtools/rust/rust-source-1.10.0.inc, recipes-devtools/rust/rust-source-1.12.1.inc, recipes-devtools/rust/rust.inc, recipes-devtools/rust/rust_1.10.0.bb, recipes-devtools/rust/rust_1.12.1.bb
=> Rust 1.12.1

classes/rust-bin.bbclass
Once we get this back into a working state, I'll propose some unit tests we can add to ensure it stays working.
=> Fix rust-bin.bbclass

conf/layer.conf, scripts/cleanup-env.sh
Found using the yocto compat script.
=> layer.conf: add the openembedded-layer to the depends since we use libgit2 from there

scripts/cleanup-env.sh, scripts/publish-build-cache.sh
Signed-off-by: Derek Straka <derek@asterius.io>
=> Add debug information to troubleshoot jenkins issues

conf/layer.conf
To support current master builds.
Signed-off-by: Aníbal Limón <anibal.limon@linaro.org>
=> conf/layer.conf: Add thud to the LAYERSERIES_COMPAT

classes/cargo_common.bbclass
While /bin/sh -> dash, var-EXTERNALSRC didn't work
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
=> cargo_common.bbclass: fix bashism

recipes-devtools/rust/rust-llvm/0002-llvm-allow-env-override-of-exe-path.patch
=> rust-llvm: Update the sysroot patch to latest from meta-clang

classes/cargo_common.bbclass
I somehow managed to conjure away a $ in the last pull request, breaking support for http proxy.
=> Correct proxy variable

recipes-devtools/cargo/cargo/0001-Disable-http2.patch
Signed-off-by: Andrei Gherzan <andrei@balena.io>
=> cargo: Refresh patch to avoid build warning

conf/layer.conf
=> layer.conf: Mark compatible with zeus release

recipes-devtools/cargo/cargo-1.39.0/0001-Disable-http2.patch
Fixes:
WARNING: Fuzz detected:
checking file Cargo.toml
Hunk #1 succeeded at 24 with fuzz 1.
Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
=> cargo: Refresh http2 disable patch

recipes-devtools/cargo/cargo-1.40.0/0001-Disable-http2.patch, recipes-devtools/cargo/cargo_1.40.0.bb, recipes-devtools/rust/libstd-rs_1.40.0.bb, recipes-devtools/rust/rust-cross_1.40.0.bb, recipes-devtools/rust/rust-llvm.inc, recipes-devtools/rust/rust-llvm_1.40.0.bb, recipes-devtools/rust/rust-snapshot-1.40.0.inc, recipes-devtools/rust/rust-source-1.40.0.inc, recipes-devtools/rust/rust.inc, recipes-devtools/rust/rust_1.40.0.bb
Depends on https://github.com/meta-rust/meta-rust/pull/257
=> Update to Rust 1.40.0

recipes-devtools/cargo/cargo-1.41.0/0001-Disable-http2.patch, recipes-devtools/cargo/cargo_1.41.0.bb, recipes-devtools/rust/libstd-rs_1.41.0.bb, recipes-devtools/rust/rust-cross_1.41.0.bb, recipes-devtools/rust/rust-llvm_1.41.0.bb, recipes-devtools/rust/rust-snapshot-1.41.0.inc, recipes-devtools/rust/rust-source-1.41.0.inc, recipes-devtools/rust/rust_1.41.0.bb
A new month and a new Rust version :)
This update is already running successfully on multiple ARM and Intel platforms at work.
=> Update to Rust 1.41.0

conf/layer.conf
=> layer.conf: Mark it 3.1 release compatible

recipes-devtools/cargo/cargo-1.43.0/0001-Disable-http2.patch, recipes-devtools/cargo/cargo_1.43.0.bb, recipes-devtools/rust/libstd-rs_1.43.0.bb, recipes-devtools/rust/rust-cross_1.43.0.bb, recipes-devtools/rust/rust-llvm_1.43.0.bb, recipes-devtools/rust/rust-snapshot-1.43.0.inc, recipes-devtools/rust/rust-source-1.43.0.inc, recipes-devtools/rust/rust_1.43.0.bb
Signed-off-by: Alistair Francis <alistair@alistair23.me>
=> Bump to Rust version 1.43

conf/layer.conf, recipes-devtools/rust/rust-llvm.inc
=> layer.conf: Add gatesgarth to LAYERSERIES_COMPAT

conf/distro/include/rust_versions.inc, recipes-devtools/cargo/cargo_1.49.0.bb, recipes-devtools/rust/rust-snapshot-1.49.0.inc, recipes-devtools/rust/rust-source-1.49.0.inc, recipes-devtools/rust/rust.inc, recipes-devtools/rust/rust_1.49.0.bb
Depends on https://github.com/meta-rust/meta-rust/pull/300 and combines https://github.com/meta-rust/meta-rust/pull/293.
@jmesmon I guess the easiest way is to merge #300, then #293, then I'll rebased this one with what's left.
=> Cleanups with 1.49.0 version.

recipes-devtools/rust/rust.inc
=> Remove checks for Rust versions we don't build anymore.

conf/layer.conf
=> layer.conf: add hardknott to compatible release branches

.github/workflows/main.yml
Verify that rust-hello-world build (which in turn ensures that
rust-native, cargo-native, etc all build)
=> Enable a workflow to build rust-hello-world

recipes-devtools/rust/rust-llvm.inc, recipes-devtools/rust/rust-llvm_1.49.0.bb, recipes-devtools/rust/rust-llvm_1.51.0.bb
=> rust-llvm: Update LLVM_RELEASE to accurate versions

.github/workflows/main.yml
This adds a basic SDK functionality test including build, installation and a test crate build.
Closes #332.
Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>
=> workflows: Build and test SDK

.github/workflows/main.yml
- Split out the build configuration job
- Use the official sstate mirror
<strike>- Disable more of unnecessary features</strike>
Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>
=> workflows: Refactor yml to improve build time

.github/workflows/main.yml, conf/layer.conf
=> conf/layer.conf: add mickledore
